# Generated by Django 4.2.7 on 2025-10-29 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_inmuebles', models.BooleanField(default=True)),
                ('notif_contratos', models.BooleanField(default=True)),
                ('notif_pagos', models.BooleanField(default=True)),
                ('notif_mantenimientos', models.BooleanField(default=True)),
                ('notif_mensajes', models.BooleanField(default=True)),
                ('email_inmuebles', models.BooleanField(default=False)),
                ('email_contratos', models.BooleanField(default=True)),
                ('email_pagos', models.BooleanField(default=True)),
                ('email_mantenimientos', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('sistema', 'Sistema'), ('inmueble', 'Inmueble'), ('contrato', 'Contrato'), ('pago', 'Pago'), ('mantenimiento', 'Mantenimiento'), ('mensaje', 'Mensaje')], default='sistema', max_length=20)),
                ('enlace', models.CharField(blank=True, max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta')], default='normal', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx'), models.Index(fields=['-fecha_creacion'], name='notificacio_fecha_c_667613_idx')],
            },
        ),
    ]
