# Generated by Django 4.2.7 on 2025-10-29 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pago', models.CharField(blank=True, max_length=50, unique=True)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mora', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('parcial', 'Pago Parcial')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('referencia_pago', models.CharField(blank=True, max_length=100)),
                ('cuenta_cobro_generada', models.BooleanField(default=False)),
                ('fecha_generacion_cuenta', models.DateTimeField(blank=True, null=True)),
                ('archivo_cuenta_cobro', models.FileField(blank=True, null=True, upload_to='cuentas_cobro/')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('comprobante', models.FileField(blank=True, upload_to='comprobantes/')),
                ('notas', models.TextField(blank=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='pagos.pago')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Registros de Pagos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
