[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = [
    "mkdir -p staticfiles",
    "chmod +x start.sh"
]

[start]
cmd = "./start.sh"

# Forzar rebuild limpio para Railway - Python 3.11
