[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = [
    "mkdir -p staticfiles",
    "python manage.py collectstatic --noinput --clear",
    "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn inmueblesapp.wsgi:application --bind 0.0.0.0:${PORT:-8000}"
