# Generated by Django 4.2.7 on 2025-10-29 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('local', 'Local Comercial'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('otro', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('arrendado', 'Arrendado'), ('mantenimiento', 'En Mantenimiento'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('area', models.DecimalField(decimal_places=2, help_text='Área en m²', max_digits=10)),
                ('habitaciones', models.IntegerField(default=0)),
                ('banos', models.IntegerField(default=0)),
                ('parqueaderos', models.IntegerField(default=0)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('precio_arriendo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_administracion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposito_seguridad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amoblado', models.BooleanField(default=False)),
                ('mascotas_permitidas', models.BooleanField(default=False)),
                ('agua_incluida', models.BooleanField(default=False)),
                ('luz_incluida', models.BooleanField(default=False)),
                ('gas_incluida', models.BooleanField(default=False)),
                ('internet_incluido', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles_propietario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ImagenInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inmuebles/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('principal', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inmuebles.inmueble')),
            ],
            options={
                'verbose_name': 'Imagen de Inmueble',
                'verbose_name_plural': 'Imágenes de Inmuebles',
                'ordering': ['orden', '-principal'],
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='inmuebles.inmueble')),
            ],
            options={
                'verbose_name': 'Característica Adicional',
                'verbose_name_plural': 'Características Adicionales',
            },
        ),
    ]
