# Generated by Django 4.2.7 on 2025-10-29 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(blank=True, max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('pintura', 'Pintura'), ('cerrajeria', 'Cerrajería'), ('limpieza', 'Limpieza'), ('electrodomestico', 'Electrodomésticos'), ('estructura', 'Estructura'), ('otro', 'Otro')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('ubicacion_especifica', models.CharField(blank=True, help_text='Ej: Cocina, Baño principal, etc.', max_length=200)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('responsable_costo', models.CharField(choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino'), ('compartido', 'Compartido')], default='propietario', max_length=20)),
                ('notas_propietario', models.TextField(blank=True)),
                ('solucion_aplicada', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mantenimientos/')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inmuebles.inmueble')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='seguimientos/')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='mantenimientos.mantenimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Mantenimiento',
                'verbose_name_plural': 'Seguimientos de Mantenimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
