# Generated by Django 4.2.7 on 2025-10-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(blank=True, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_firma', 'Pendiente de Firma'), ('activo', 'Activo'), ('vencido', 'Vencido'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('valor_arriendo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_administracion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_deposito', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_pago', models.IntegerField(default=5, help_text='Día del mes para pago')),
                ('firma_propietario', models.TextField(blank=True, help_text='Firma digital del propietario')),
                ('fecha_firma_propietario', models.DateTimeField(blank=True, null=True)),
                ('firma_inquilino', models.TextField(blank=True, help_text='Firma digital del inquilino')),
                ('fecha_firma_inquilino', models.DateTimeField(blank=True, null=True)),
                ('terminos_condiciones', models.TextField()),
                ('clausulas_especiales', models.TextField(blank=True)),
                ('documento_contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FirmaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_base64', models.TextField(help_text='Firma en formato base64')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Firma Digital',
                'verbose_name_plural': 'Firmas Digitales',
            },
        ),
    ]
