# Generated by Django 4.2.7 on 2025-10-29 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmuebles', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmadigital',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='inmuebles.inmueble'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_inquilino', to=settings.AUTH_USER_MODEL),
        ),
    ]
