# Generated by Django 4.2.7 on 2025-11-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_solicitudarriendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='motivo_cierre',
            field=models.TextField(blank=True),
        ),
    ]
